apiVersion: v1
kind: Service
metadata:
  name: kubecon-api-ratings
  labels:
    name: kubecon-api-ratings
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: kubecon-api-ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecon-api-ratings
  labels:
    app: kubecon-api-ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecon-api-ratings
  template:
    metadata:
      labels:
        app: kubecon-api-ratings
    spec:
      containers:
      - env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: cosmos-db-secret
              key: uri
        - name: PORT
          value: "8080"
        image: chzbrgr71/kubecon-api-ratings:v2
        imagePullPolicy: Always
        name: kubecon-api-ratings
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kubecon-api-sites
  labels:
    name: kubecon-api-sites
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: kubecon-api-sites
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecon-api-sites
  labels:
    app: kubecon-api-sites
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecon-api-sites
  template:
    metadata:
      labels:
        app: kubecon-api-sites
    spec:
      containers:
      - env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: cosmos-db-secret
              key: uri
        - name: PORT
          value: "8080"
        image: chzbrgr71/kubecon-api-sites
        imagePullPolicy: Always
        name: kubecon-api-sites
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kubecon-api-subjects
  labels:
    name: kubecon-api-subjects
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: kubecon-api-subjects
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecon-api-subjects
  labels:
    app: kubecon-api-subjects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecon-api-subjects
  template:
    metadata:
      labels:
        app: kubecon-api-subjects
    spec:
      containers:
      - env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: cosmos-db-secret
              key: uri
        - name: PORT
          value: "8080"
        image: chzbrgr71/kubecon-api-subjects
        imagePullPolicy: Always
        name: kubecon-api-subjects
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always